# Generated by Django 3.0.5 on 2020-05-06 10:48

from django.db import migrations

def populate_db(apps, schema_editor):
    Device = apps.get_model('dashboard', 'Device')
    device1 = Device(device_id=1)
    device1.save()
    device2 = Device(device_id=2)
    device2.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_intensitydata'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
